### ISSUE TITLE
The isHoliday() does not work

### ISSUE THREAD

**Issue by Rmcouto** [reediculous456/dayjs-business-days#1]
Hi there,

I installed the 'dayjs-business-days2' equal repo GIT but during usage does works well.

_ _ Step by step _ _
```js
import businessDays from 'dayjs-business-days2'

dayjs.extend(businessDays);

const july4th = '2020-07-04'
const options = {
  holidays: [july4th],
  holidayFormat: `YYYY-MM-DD`
};
dayjs.extend(businessDays, options);
```
But in the Console >> console.log("Date true/false : " + dayjs('2020-07-04T00:00:00.000').isHoliday()); always returns "false".

Can you help me with this please?

Thanks.

**Comment by reediculous456** [comment]
Can you share your NodeJS version, your dayjs version, and your version of dayjs-business-days2

**Comment by reediculous456** [comment]
Actually I think I found your issue.
You're calling `dayjs.extend(businessDays)` and then `dayjs.extend(businessDays, options)` and dayjs does not support calling extend twice on the same plugin. you should remove the extra extend call and it should work as intended
