### ISSUE TITLE
WARNING in terminal due to 'dayjs-business-days2'

### ISSUE THREAD

**Issue by nithinsanjey** [reediculous456/dayjs-business-days#10]
I am using the latest version of dayjs-business-days2 - (version 1.2.0)

I get the below warning in terminal when I run the app with `npm start` in my react project.

WARNING in ./node_modules/dayjs-business-days2/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\<folder_name>\<project_name>\node_modules\dayjs-business-days2\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\<folder_name>\<project_name>\node_modules\dayjs-business-days2\src\index.ts'

I tried switching to version 1.1.0 and got the same warning.

I do not want to see any error/warning messages when compiling the app. Is this a issue with 'dayjs-business-days2' package?

**Comment by reediculous456** [comment]
Hello, I have found the issue causing this warning an will be releasing v1.2.1 soon to address it
