### ISSUE TITLE
Not compatible with dayjs `1.11.4`

### ISSUE THREAD

**Issue by zomars** [reediculous456/dayjs-business-days#3]
Getting the following type error when using this plugin version `1.1.1` with dayjs `1.11.4`:

```
Argument of type 'import("/Users/zomars/Sites/cal.com/node_modules/dayjs-business-days2/node_modules/dayjs/index").PluginFunc<unknown>' is not assignable to parameter of type 'import("/Users/zomars/Sites/cal.com/node_modules/dayjs/index").PluginFunc<unknown>'.
  Types of parameters 'c' and 'c' are incompatible.
    Type 'typeof import("/Users/zomars/Sites/cal.com/node_modules/dayjs/index").Dayjs' is not assignable to type 'typeof import("/Users/zomars/Sites/cal.com/node_modules/dayjs-business-days2/node_modules/dayjs/index").Dayjs'.
      Types of construct signatures are incompatible.
        Type 'new (config?: string | number | Dayjs | Date | null | undefined) => Dayjs' is not assignable to type 'new (config?: string | number | Dayjs | Date | null | undefined) => Dayjs'.
          Types of parameters 'config' and 'config' are incompatible.
            Type 'string | number | import("/Users/zomars/Sites/cal.com/node_modules/dayjs-business-days2/node_modules/dayjs/index").Dayjs | Date | null | undefined' is not assignable to type 'string | number | import("/Users/zomars/Sites/cal.com/node_modules/dayjs/index").Dayjs | Date | null | undefined'.
              Type 'Dayjs' is not assignable to type 'string | number | Dayjs | Date | null | undefined'.
                Type 'Dayjs' is missing the following properties from type 'Dayjs': isBetween, isToday, fromNow, from, and 8 more.ts(2345)
```

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/3504472/184456445-76db78cf-9535-472e-b34c-4ad748633e64.png">

**Comment by zomars** [comment]
Seems like locking to these version do the trick:

```
"dayjs": "1.11.2",
"dayjs-business-days2": "1.1.0"
```

**Comment by reediculous456** [comment]
I'm using plugin version `1.1.1` with dayjs `1.11.4` without any issues, can you provide your ts config?

**Comment by reediculous456** [comment]
Also, can you provide the full context of where you are extending dayjs? I'd like to see your import statement as well as any other plugins you may be using

**Comment by reediculous456** [comment]
Here's a link to a code sandbox where this works as intended: https://codesandbox.io/s/dayjs-business-days2-issue-3-if4xyh?file=/package.json (see the console tab)

**Comment by zomars** [comment]
Sure, you can see our [full implementation here](https://github.com/calcom/cal.com/blob/main/packages/dayjs/index.ts)

**Comment by reediculous456** [comment]
Can you point me to the tsconfig file in that project? (also sorry for the super delayed reply 😅)

**Comment by zomars** [comment]
> Can you point me to the tsconfig file in that project? (also sorry for the super delayed reply 😅)

It's ok, this package is being used in multiple apps in the monorepo so tsconfig files may vary. But [here is one of the main ones](https://github.com/calcom/cal.com/blob/main/apps/web/tsconfig.json).

**Comment by reediculous456** [comment]
Everything looks normal to me, I'm going to clone your repo and try to run it on my machine to see if I can replicate the issue

**Comment by reediculous456** [comment]
So I am able to replicate this on `dayjs@1.11.4` and `dayjs-business-days2@1.1.0` using your repo, however upgrading to `dayjs@1.11.5` and `dayjs-business-days2@1.1.1` solves the problem for me so that's what I would recommend

**Comment by zomars** [comment]
Will try in the next upgrade release. Thanks @reediculous456 🙏🏽

**Comment by ottob** [comment]
I started getting this error when I bumped to 1.11.13, if I pin it to 1.11.12 it works.

**Comment by reediculous456** [comment]
> I started getting this error when I bumped to 1.11.13, if I pin it to 1.11.12 it works.

Do you mind opening a new issue for me?
