### ISSUE TITLE
not working with typescript react

### ISSUE THREAD

**Issue by aimeetacchi** [reediculous456/dayjs-business-days#4]
I have a react typescript project I've installed it and tried to use it.

I am getting this when trying to do 

`dayjs(date).isBusinessDay()`

`Property 'isBusinessDay' does not exist on type 'Dayjs'.`

**Comment by reediculous456** [comment]
I'm unable to replicate this, can you let me know the version of:
- React
- Typescript
- Node
- Dayjs
- My plugin

If your code is public you could also share a link and that might help me replicate it. Otherwise you could make an SCCE and share it

**Comment by aimeetacchi** [comment]
> I'm unable to replicate this, can you let me know the version of:
> 
> * React
> * Typescript
> * Node
> * Dayjs
> * My plugin
> 
> If your code is public you could also share a link and that might help me replicate it. Otherwise you could make an SCCE and share it

Hi @reediculous456 
I'm using

 "react": "^17.0.2",
"typescript": "^4.4.2"
"dayjs": "1.11.4",
"@types/node": "^16.11.36",
 "@types/react": "^17.0.2",
"@types/react-dom": "^17.0.2",


your plugin latest

node - v14.17.3

**Comment by reediculous456** [comment]
With all the versions specified I cannot replicate the issue: https://codesandbox.io/s/dayjs-business-days2-issue-4-h3tqkn

**Comment by aimeetacchi** [comment]
> With all the versions specified I cannot replicate the issue: https://codesandbox.io/s/dayjs-business-days2-issue-4-h3tqkn

hmmm how odd.. I'll have to try again. Thanks though

**Comment by reediculous456** [comment]
I'll close this issue for now, if you find a reproducible case just comment back on it
