### ISSUE TITLE
feat: hope to support setting additional working days

### ISSUE THREAD

**Issue by superche** [reediculous456/dayjs-business-days#6]
### Describe the feature you'd like to request

Sometime, there are official additional working days to compensate for the long holiday break. I hope to support setting additional working days, and update `isBusinessDay`. I think it would be useful.

Use case example.

During Chinese New Year 2023, Chinese official holiday and additional working days are:

- holiday: from Jan 21 to Jan 27
- additional working days: Jan 28, Jan 29

ref: https://calendars.icloud.com/holidays/cn_zh.ics

### Describe the solution you'd like to see

new API: setAdditionalWorkingDays() => void

Sets the additional working day list to the given array of strings
```
dayjs.setAdditionalWorkingDays([ `2023-01-28`, `2023-01-29` ]);
```

update API: isBusinessDay

after setAdditionalWorkingDays
```
dayjs(`2023-01-28`).isBusinessDay(); // returns true
```

**Comment by reediculous456** [comment]
Based on my understanding of the ask here, you would set your normal working days (ex. Mon-Fri) and then use the additional days property to tell the package you will be working a one-off Sat-Sun

Can you please confirm if my example lines up with what you're asking for?

**Comment by superche** [comment]
> Based on my understanding of the ask here, you would set your normal working days (ex. Mon-Fri) and then use the additional days property to tell the package you will be working a one-off Sat-Sun
> 
> Can you please confirm if my example lines up with what you're asking for?

Correct. 
In the example "Chinese New Year 2023", additional working days are Jan 28, Jan 29. Those additional working days are one-off.
"Chinese New Year 2024" additional working days may be not Jan 28, Jan 29.
